"""add styling column

Revision ID: 160f5aa89bf8
Revises: 6d54ea8cd4c2
Create Date: 2026-05-03 18:17:56.166249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160f5aa89bf8'
down_revision: Union[str, Sequence[str], None] = '6d54ea8cd4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_layout', sa.Column(
        'styling', 
        sa.JSON(), 
        nullable=False, 
        server_default=sa.text("""'{"color_text_name": "#1A5C71",               
        "color_accent": "#2A7F9E", 
        "font_main": ["Open Sans", "Helvetica Neue", "Arial", "sans-serif"]}'::json""")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_layout', 'styling')
    # ### end Alembic commands ###
