"""add styling to resume

Revision ID: 316f28c2e6e1
Revises: d8d61094ae8a
Create Date: 2026-05-28 19:35:18.759169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316f28c2e6e1'
down_revision: Union[str, Sequence[str], None] = 'd8d61094ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column(
        'styling', sa.JSON(), 
        nullable=True,
        )
    )

    # add users' currently selected stylings to each resume
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE resume 
        SET styling = user_layout.styling 
        FROM user_layout 
        WHERE resume.user_id = user_layout.user_id
    """))
    conn.execute(
        sa.text("UPDATE resume SET styling = :s WHERE styling IS NULL"),
        {"s": '{"color_text_name": "#1A5C71", "color_accent": "#2A7F9E", '
            '"font_main": ["Open Sans", "Helvetica Neue", "Arial", "sans-serif"]}'},
    )
    op.alter_column("resume", "styling", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'styling')
    # ### end Alembic commands ###
