"""add user_layout table and resume.layout column

Revision ID: 6d54ea8cd4c2
Revises: e78a28a66fc1
Create Date: 2026-04-26 17:08:34.095619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d54ea8cd4c2'
down_revision: Union[str, Sequence[str], None] = 'e78a28a66fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    DEFAULT_LAYOUT_JSON = """[
        {"name": "summary", "enabled": true, "ordering": 0},
        {"name": "jobs", "enabled": true, "ordering": 1},
        {"name": "education", "enabled": true, "ordering": 2},
        {"name": "projects", "enabled": true, "ordering": 3},
        {"name": "skills", "enabled": true, "ordering": 4}
      ]"""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_layout',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.execute(f"""
        INSERT INTO user_layout (id, user_id, layout)
        SELECT gen_random_uuid(), id, '{DEFAULT_LAYOUT_JSON}'::json
        FROM user_account
    """)
    op.add_column(
          'resume',                                                                                              
          sa.Column(                     
              'layout',                                                                                          
              sa.JSON(),
              nullable=False,                                                                                    
              server_default=sa.text(f"'{DEFAULT_LAYOUT_JSON}'::json"),
          )                                                                                                      
      )
    op.alter_column('resume', 'layout', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'layout')
    op.drop_table('user_layout')
    # ### end Alembic commands ###
